sudo: required
language: generic

services:
    - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    
before_install:
    #Command to make use of the file encrypted by Travis.
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    #Set Google Cloud locally.
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    #To be able to make use of the kubectl command.
    - gcloud components update kubectl
    #Authorization to Google Cloud account. The credentials are going to be given through the service-account.json file.
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project multi-k8s-282809
    - gcloud config set compute/zone europe-west3-b 	
    - gcloud container clusters get-credentials multi-cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
    #We use the development version because it is the only one that containes the tools required for running tests.
    - docker build -t carlosalonsogtz/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true carlosalonsogtz/react-test npm run test


deploy:
    #edge: true
    #Since there is no built-in provider for a Kubernetes cluster, we have to do the deployment ourselves.
    #provider: elasticbeanstalk
    provider: script
    script: bash ./deploy.sh
    # region: "us-east-2"
    # app: "multi-docker"
    # env: "MultiDocker-env-1"
    # bucket_name: "elasticbeanstalk-us-east-2-784097295211"
    # bucket_path: "docker-multi"
    on:
        branch: master